### ISSUE TITLE
[Loans] Query loans by multiple loan states

### ISSUE THREAD

**Issue by thedonatello** [BendDAO/bend-protocol-subgraph#1]
**Is your feature request related to a problem? Please describe.**
Subgraph doesn't support query `Loans` by multiple Loan states. Feature is needed to query loans by two or more loan states serverside, to support infinite pagination. Currently it's supported to query only by one (1) loan state.

**Describe the solution you'd like**
Add input parameter loanState_in. Some other queries support such input parameter.
```
query Loans($borrower: String, $first: Int, $skip: Int) {
  loans(where: { borrower: $borrower, loanState_in: [Active, Auction] }, first: $first, skip: $skip) {
    ...
}
```

**Comment by thorseldon** [comment]
we need to upgrade graph-node version to v0.25.0 at lease, which should support enum filter in and not_in.

https://github.com/graphprotocol/graph-node/pull/2841

**Comment by thedonatello** [comment]
Feature added to frontend.
